### ISSUE TITLE
Complete modbus map

### ISSUE THREAD

**Issue by xavi104** [InfernoEmbedded/PowerScraper#13]
Hi Guys,

congratulation for your work! I have installed in my house a Solax hybrid x1 T5 inverterter with a triple power battery. Now I can monitorize and control it with my home assistant. 
I am looking for the entire modbus map of solax inverter to try to improve and share my project taking access to other registers. Where can I find it?

thanks in advance!

**Comment by deece** [comment]
You'll need to talk to a Solax engineer. The documentation was provided to me on the condition that I don't redistribute it.
