### ISSUE TITLE
Getting data in emoncms

### ISSUE THREAD

**Issue by MrHappy** [InfernoEmbedded/PowerScraper#4]
Looks like everything is working (no errors 👍 ), but I don't see any data in emoncms.
How can I resolve this??

**Comment by deece** [comment]
It should have created new inputs in EmonCMS, which you can then create feeds from.

**Comment by MrHappy** [comment]
Weird, cause I don't see anything in logging or displayed on screen.
Is there anyway to show logging on screen?

**Comment by deece** [comment]
You could remove the comment on the debug line in Outputs/EmonCMS.py:http error(). That should give you more info as to what is going on, if the http request to emoncms is failing

**Comment by MrHappy** [comment]
If you mean the line with "#    print("Error: " + error.getErrorMessage + "\n Trace:\n" + error.getTraceback()):", I removed the comment and it showed nothing after running the script again... It justs 'hangs'...

**Comment by deece** [comment]
Can you post your config, and a screenshot of your EmonCMS inputs list?

**Comment by MrHappy** [comment]
My config (these are lines with no comment-pound in front:
`# Enable this section to scrape the Wifi interface of Solax inverters
[solax-Wifi]
poll_period = 10 # seconds
timeout = 5 # seconds
inverters = ['192.168.254.50']

# Enable this section to output to EmonCMS
[emoncms]
timeout = 5 # seconds
server = "http://172.16.4.109/emoncms"
api_key = "<api-key>"
`
The input screen is empty except for input delivered by P1 Datalogger (which reeds my smartmeter)

**Comment by MrHappy** [comment]
I think I've found the solution.... There is a inconsistency in the variable-name Solax-Wifi/solax-Wifi... It is case-sensitive apparently. Changed them all so they match and now they pop up.

**Comment by deece** [comment]
It's worth pointing out that you get much more information over the Ethernet port then Wifi

**Comment by mfcltd** [comment]
> I think I've found the solution.... There is a inconsistency in the variable-name Solax-Wifi/solax-Wifi... It is case-sensitive apparently. Changed them all so they match and now they pop up.

I have only found one inconsistency in the case, and it has at 

> Setting up EmonCMS

Did you get passed this?

**Comment by MrHappy** [comment]
> 
> 
> > I think I've found the solution.... There is a inconsistency in the variable-name Solax-Wifi/solax-Wifi... It is case-sensitive apparently. Changed them all so they match and now they pop up.
> 
> I have only found one inconsistency in the case, and it has at
> 
> > Setting up EmonCMS
> 
> Did you get passed this?

Like I mentioned, after changing the variable name it worked.

**Comment by mfcltd** [comment]
Can I ask which Solax inverter you have and how you are connecting to it? 

I have the X1-AC which has the Pocket WiFi dongle.

**Comment by MrHappy** [comment]
A X1-3.0-T with a pocket wifi dongle.
